### ISSUE TITLE
removing MFA methods

### ISSUE THREAD

**Issue by beckycaret** [mrobinson-ws/usertermination-azuread#10]
Hey there !  Was hoping you could add a couple lines to remove MFA/recovery email and phone from AzureAD

**Comment by mrobinson-ws** [comment]
Becky,

This would add a 4th connection - directly to Graph.  I'll keep digging but it is a major feature update, so may take some time.

**Comment by mrobinson-ws** [comment]
Also, only phone methods are accessible, this may need to stay a Portal function.

**Comment by mrobinson-ws** [comment]
Closing, this needs to stay in the portal as Powershell cannot access all methods.
