### ISSUE TITLE
Redundant calls for getting groups information

### ISSUE THREAD

**Issue by robertwitteman** [mrobinson-ws/usertermination-azuread#2]
`142: $memberships = Get-AzureADUser -SearchString $username | Get-AzureADUserMembership | Where-Object {$_.ObjectType -ne "Role"}  | ForEach-Object {Get-AzureADGroup -ObjectId $_.ObjectId | Select-Object DisplayName,ObjectId}`

1. Calling `Get-AzureADUser -SearchString $username` to pipe into `Get-AzureADUserMembership`, except you could directly call `Get-AzureADUserMembership -ObjectId $username`
2. Calling `Get-AzureADGroup` inside `ForEach-Object` is redundant, you already have the Groups from the call to `Get-AzureADUserMembership`.

**Comment by mrobinson-ws** [comment]
The -Searchstring username is how I filter out the roles, it's ONLY pulling groups - I am not sure how to do a searchstring that way to filter out the roles otherwise, that was all I could figure out

**Comment by robertwitteman** [comment]
You can do `Get-AzureAdUserMembership -ObjectId $username` without the first call to get the user first (again).

**Comment by mrobinson-ws** [comment]
I have to leave the foreach in the filter, no idea why, but it does not work without it, I have fixed the rest, I'll let you look again

**Comment by mrobinson-ws** [comment]
Updated line to

$memberships = Get-AzureADUserMembership -ObjectId $username | Where-Object {$_.ObjectType -ne "Role"}| Select-Object DisplayName,ObjectId

Also on line 159 currently, not 142
