### ISSUE TITLE
Filtering out dynamic membership Microsoft 365 groups

### ISSUE THREAD

**Issue by robertwitteman** [mrobinson-ws/usertermination-azuread#9]
Has this been tested?

```
$group = Get-AzureADMSGroup -ID $membership.ObjectId
if ($group -eq 'DynamicMembership') {
     Write-Verbose "Skipping $group.Displayname as it is dynamic"
}
```

`$group` is a Azure AD Group object with various properties, one of them being `GroupType` which might contain `DynamicMembership`. Comparing `$group` to `DynamicMembership` is not a proper evaluation.

**Comment by mrobinson-ws** [comment]
Yes, it works, the azureadmsgroup returns that if it's dynamic, I only tested on the test tenant but it works

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>


Mike Robinson

Technical Support Engineer

888-484-1012<tel:888-484-1012>

Need technical support? Create a ticket: ***@***.******@***.***>


[cid:Worksmart_EmailLogo_BlueTint_b83f0a42-5757-48b3-8f2b-71adc2076ca0.png] <https://www.worksmart.com>         [cid:BlueTint_Twitter_3c1c14f8-b984-4094-b5a6-288e240090cf.png]  <https://twitter.com/WorkSmart_Inc>            [cid:BlueTint_Facebook_db780300-f919-49b8-8991-f455a59ed5f5.png]  <https://www.facebook.com/WorkSmartIT>        [cid:BlueTint_LinkedIn_f65d91e1-72e4-4d42-95b3-a7c7f8ff56f2.png]  <https://www.linkedin.com/company/worksmart/>         [cid:BlueTint_Instagram_5c8d385a-57b0-4520-aaef-db97f973a950.png]  <https://www.instagram.com/worksmart.it.made.simple/>


 [cid:MicrosoftTeams-image(1)_af07553a-1f46-41fe-a4d3-070e7f30b2ad.png] <https://www.worksmart.com/webinars/> <https://info.worksmart.com/refersmart> <https://blog.worksmart.com/worksmart-continues-managed-it-services-expansion-in-atlanta> <https://blog.worksmart.com/knowledgecenter/phish-proof-cybersecurity-awareness-training> <https://info.worksmart.com/filesinthecloud> <https://info.worksmart.com/cybersecurity-awareness-month-week-2> <https://info.worksmart.com/worksmart-live-thats-a-wrap> <https://info.worksmart.com/worksmart-live-phish-proof> <https://info.worksmart.com/worksmart-live-to-security-and-beyond> <https://info.worksmart.com/worksmart-live-teams-for-everyday-people-part-2> <https://info.worksmart.com/worksmart-live-teams-for-everyday-people-part-1> <https://info.worksmart.com/leading-culture> <https://info.worksmart.com/backup-to-basics> <https://info.worksmart.com/files-files-everywhere> <https://info.worksmart.com/communicating-in-the-cloud> <https://info.worksmart.com/to-be-or-not-to-be-acquisitions> <https://info.worksmart.com/virtual-reality-strategy> <https://info.worksmart.com/virtual-reality-strategy>




________________________________
From: majorwitteman ***@***.***>
Sent: Sunday, June 6, 2021 10:36:36 PM
To: mrobinson-ws/usertermination-azuread ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External][mrobinson-ws/usertermination-azuread] Filtering out dynamic membership Microsoft 365 groups (#9)


Has this been tested?

$group = Get-AzureADMSGroup -ID $membership.ObjectId
if ($group -eq 'DynamicMembership') {
     Write-Verbose "Skipping $group.Displayname as it is dynamic"
}


$group is a Azure AD Group object with various properties, one of them being GroupType which might contain DynamicMembership. Comparing $group to DynamicMembership is not a proper evaluation.

**Comment by robertwitteman** [comment]
Are you sure though? Take the following demo example for consideration:

```
PS> $group = Get-AzureADMSGroup -SearchString "test dynamic"

PS> $group | fl *

Id                           : 037ede18-4e73-4d94-864e-9e19babcff47
OdataType                    :
Description                  : Test Dynamic
OnPremisesSyncEnabled        :
DisplayName                  : Test Dynamic
OnPremisesLastSyncDateTime   :
Mail                         : TestDynamic@robwittemandev.onmicrosoft.com
MailEnabled                  : True
MailNickname                 : TestDynamic
OnPremisesSecurityIdentifier :
ProxyAddresses               : {SMTP:TestDynamic@robwittemandev.onmicrosoft.com}
SecurityEnabled              : True
GroupTypes                   : {DynamicMembership, Unified}
Visibility                   : Public
CreatedDateTime              : 6/7/2021 3:06:24 AM
RenewedDateTime              : 6/7/2021 3:06:24 AM

PS> $group.GroupTypes
DynamicMembership
Unified

PS> if ($group -eq "DynamicMembership") { $true } else { $false }
False

PS> if ($group.GroupTypes -eq "DynamicMembership") { $true } else { $false }
True
```

**Comment by mrobinson-ws** [comment]
I think I had grouptype and it lost it in a merge bleh

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>


Mike Robinson

Technical Support Engineer

888-484-1012<tel:888-484-1012>

Need technical support? Create a ticket: ***@***.******@***.***>


[cid:Worksmart_EmailLogo_BlueTint_b83f0a42-5757-48b3-8f2b-71adc2076ca0.png] <https://www.worksmart.com>         [cid:BlueTint_Twitter_3c1c14f8-b984-4094-b5a6-288e240090cf.png]  <https://twitter.com/WorkSmart_Inc>            [cid:BlueTint_Facebook_db780300-f919-49b8-8991-f455a59ed5f5.png]  <https://www.facebook.com/WorkSmartIT>        [cid:BlueTint_LinkedIn_f65d91e1-72e4-4d42-95b3-a7c7f8ff56f2.png]  <https://www.linkedin.com/company/worksmart/>         [cid:BlueTint_Instagram_5c8d385a-57b0-4520-aaef-db97f973a950.png]  <https://www.instagram.com/worksmart.it.made.simple/>


 [cid:MicrosoftTeams-image(1)_af07553a-1f46-41fe-a4d3-070e7f30b2ad.png] <https://www.worksmart.com/webinars/> <https://info.worksmart.com/refersmart> <https://blog.worksmart.com/worksmart-continues-managed-it-services-expansion-in-atlanta> <https://blog.worksmart.com/knowledgecenter/phish-proof-cybersecurity-awareness-training> <https://info.worksmart.com/filesinthecloud> <https://info.worksmart.com/cybersecurity-awareness-month-week-2> <https://info.worksmart.com/worksmart-live-thats-a-wrap> <https://info.worksmart.com/worksmart-live-phish-proof> <https://info.worksmart.com/worksmart-live-to-security-and-beyond> <https://info.worksmart.com/worksmart-live-teams-for-everyday-people-part-2> <https://info.worksmart.com/worksmart-live-teams-for-everyday-people-part-1> <https://info.worksmart.com/leading-culture> <https://info.worksmart.com/backup-to-basics> <https://info.worksmart.com/files-files-everywhere> <https://info.worksmart.com/communicating-in-the-cloud> <https://info.worksmart.com/to-be-or-not-to-be-acquisitions> <https://info.worksmart.com/virtual-reality-strategy> <https://info.worksmart.com/virtual-reality-strategy>




________________________________
From: majorwitteman ***@***.***>
Sent: Sunday, June 6, 2021 11:11:21 PM
To: mrobinson-ws/usertermination-azuread ***@***.***>
Cc: Mike Robinson ***@***.***>; Comment ***@***.***>
Subject: [External]Re: [mrobinson-ws/usertermination-azuread] Filtering out dynamic membership Microsoft 365 groups (#9)


Are you sure though? Take the following demo example for consideration:

PS> $group = Get-AzureADMSGroup -SearchString "test dynamic"

PS> $group | fl *

Id                           : 037ede18-4e73-4d94-864e-9e19babcff47
OdataType                    :
Description                  : Test Dynamic
OnPremisesSyncEnabled        :
DisplayName                  : Test Dynamic
OnPremisesLastSyncDateTime   :
Mail                         : ***@***.***
MailEnabled                  : True
MailNickname                 : TestDynamic
OnPremisesSecurityIdentifier :
ProxyAddresses               : ***@***.***}
SecurityEnabled              : True
GroupTypes                   : {DynamicMembership, Unified}
Visibility                   : Public
CreatedDateTime              : 6/7/2021 3:06:24 AM
RenewedDateTime              : 6/7/2021 3:06:24 AM

PS> $group.GroupTypes
DynamicMembership
Unified

PS> if ($group -eq "DynamicMembership") { $true } else { $false }
False

PS> if ($group.GroupTypes -eq "DynamicMembership") { $true } else { $false }
True

**Comment by mrobinson-ws** [comment]
Thanks, fixed it, also had 2 select lines for sharing the mailbox, I had a weird merge issue so I think that was it, good catch

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>


Mike Robinson

Technical Support Engineer

888-484-1012<tel:888-484-1012>

Need technical support? Create a ticket: ***@***.******@***.***>


[cid:Worksmart_EmailLogo_BlueTint_226a0c04-c2d9-4c8b-96ce-e9b22b9fca97.png] <https://www.worksmart.com>



________________________________
